import datetime

import launch
import launch_ros.actions

from launch.actions import (
    LogInfo,
    RegisterEventHandler,
    IncludeLaunchDescription,
    GroupAction,
)
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch.conditions import IfCondition
from launch.event_handlers import OnProcessStart
from launch_ros.substitutions import FindPackageShare
from launch_xml.launch_description_sources import XMLLaunchDescriptionSource
from launch.launch_description_sources import FrontendLaunchDescriptionSource


def generate_launch_description():

    dtcvc_scenario_node = launch_ros.actions.Node(
        package="dtcvc_scenario",
        executable="dtcvc_scenario_node",
        name="dtcvc_scenario_node",
        output="screen",
        emulate_tty="True",
        on_exit=launch.actions.Shutdown(),
        parameters=[
            {"host": LaunchConfiguration("host")},
            {"port": LaunchConfiguration("port")},
            {"file": LaunchConfiguration("scenario_file")},
            {"clean_kill": LaunchConfiguration("scenario_kill_simulator")},
            {"verbose": LaunchConfiguration("scenario_verbose")},
        ],
    )

    ld = launch.LaunchDescription(
        [
            launch.actions.DeclareLaunchArgument(
                name="log_level",
                default_value="info",
                description="Default logging level",
            ),
            launch.actions.DeclareLaunchArgument(
                name="host",
                default_value="localhost",
                description="IP of the CARLA server",
            ),
            launch.actions.DeclareLaunchArgument(
                name="port",
                default_value="2000",
                description="TCP port of the CARLA server",
            ),
            launch.actions.DeclareLaunchArgument(
                name="scenario_file",
                description="Scenario file to load into the simulator",
            ),
            launch.actions.DeclareLaunchArgument(
                name="scenario_kill_simulator",
                default_value="True",
                description="Kill the simulator when scenario completes",
            ),
            launch.actions.DeclareLaunchArgument(
                name="scenario_verbose",
                default_value="True",
                description="Enable verbose logging for the scenario manager",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_ground_truth_intake",
                default_value="True",
                description="Enable/Disable ground truth data extraction from 'ground_truth_path'. ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="ground_truth_path",
                default_value="/opt/ground_truth",
                description="Path to ground truth data directory.",
            ),
            launch.actions.DeclareLaunchArgument(
                name="record_on_startup",
                default_value="False",
                description="Enable/disable recording the simulation on startup. ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_sensor_recording",
                default_value="True",
                description="Enable/disable recording the sensor feed data (e.g. /carla/*/rgb_camera/*). ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_simulation_topic_recording",
                default_value="True",
                description="Enable/disable recording simulation topics (e.g. /carla/*). ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_competition_topic_recording",
                default_value="True",
                description="Enable/disable recording competition topics (e.g. /competitor/*). ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="recording_file_name",
                default_value=datetime.datetime.now().strftime("scenario_recording_%Y_%m_%d-%H_%M_%S.bag"),
                description="Name of the file generated by the recorder. ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_foxglove_bridge",
                default_value="False",
                description="Enable/disable a websocket-based bridge for viewing live data with foxglove 'live connection'. ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="foxglove_bridge_thread_count",
                default_value="0",
                description="If foxglove bridge enabled: Number of threads to be allocated to foxglove bridge (defaults to 0 which is one per core) ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="foxglove_bridge_buffer_limit",
                default_value="4000000000",
                description="If foxglove bridge enabled: Size of stream buffer allocated to foxglove bridge in bytes (defaults to 4000000000 which is 4 Gigabytes) ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="wait_for_competitor",
                default_value="True",
                description="Wait for competitor ready signal before starting (defaults to true)",
            ),
            launch.actions.DeclareLaunchArgument(
                name="stop_on_simulator_shutdown",
                default_value="True",
                description="Send competition stop signal when simulator is shutdown (defaults to true)",
            ),
            launch.actions.DeclareLaunchArgument(
                name="casualty_id_cap",
                default_value="30",
                description="The default capacity of unique casualty IDs that would exist for a scenario.",
            ),
            dtcvc_scenario_node,
        ]
    )
    return ld


if __name__ == "__main__":
    generate_launch_description()
