import datetime

import launch
import launch_ros.actions

from launch.actions import (
    LogInfo,
    RegisterEventHandler,
    IncludeLaunchDescription,
    GroupAction,
)
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch.event_handlers import OnProcessStart
from launch_ros.substitutions import FindPackageShare
from launch.launch_description_sources import FrontendLaunchDescriptionSource


def generate_launch_description():

    dtcvc_timekeeper_node = launch_ros.actions.Node(
        package="dtcvc_timekeeper",
        executable="dtcvc_timekeeper_node",
        name="dtcvc_timekeeper_node",
        output="screen",
        emulate_tty="True",
        on_exit=launch.actions.Shutdown(),
        parameters=[
            {"use_sim_time": True},
            {"scenario_file": LaunchConfiguration("scenario_file")},
            {"wait_for_competitor": False},
            {"wait_for_scorekeeper": False},
            {"stop_on_simulator_shutdown": True},
        ],
    )

    dtcvc_recorder_node = launch_ros.actions.Node(
        package="dtcvc_recorder",
        executable="dtcvc_recorder_node",
        name="dtcvc_recorder_node",
        output="screen",
        emulate_tty="True",
        on_exit=launch.actions.Shutdown(),
        parameters=[
            {"use_sim_time": True},
            {"record_on_startup": LaunchConfiguration("record_on_startup")},
            {"enable_scenario_recording_mode": True},
            {"enable_sensor_recording": LaunchConfiguration("enable_sensor_recording")},
            {"enable_simulation_topic_recording": LaunchConfiguration("enable_simulation_topic_recording")},
            {"enable_competition_topic_recording": LaunchConfiguration("enable_competition_topic_recording")},
            {"recording_file_name": LaunchConfiguration("recording_file_name")},
        ],
    )

    dtcvc_scenario_node = launch_ros.actions.Node(
        package="dtcvc_scenario",
        executable="dtcvc_scenario_node",
        name="dtcvc_scenario_node",
        output="screen",
        emulate_tty="True",
        on_exit=launch.actions.Shutdown(),
        parameters=[
            {"host": LaunchConfiguration("host")},
            {"port": LaunchConfiguration("port")},
            {"file": LaunchConfiguration("scenario_file")},
            {"clean_kill": LaunchConfiguration("scenario_kill_simulator")},
            {"verbose": LaunchConfiguration("scenario_verbose")},
        ],
    )

    ld = launch.LaunchDescription(
        [
            launch.actions.DeclareLaunchArgument(
                name="host",
                default_value="localhost",
                description="IP of the CARLA server",
            ),
            launch.actions.DeclareLaunchArgument(
                name="port",
                default_value="2000",
                description="TCP port of the CARLA server",
            ),
            launch.actions.DeclareLaunchArgument(
                name="scenario_file",
                description="Scenario file to load into the simulator",
            ),
            launch.actions.DeclareLaunchArgument(
                name="scenario_kill_simulator",
                default_value="True",
                description="Kill the simulator when scenario completes",
            ),
            launch.actions.DeclareLaunchArgument(
                name="scenario_verbose",
                default_value="True",
                description="Enable verbose logging for the scenario manager",
            ),
            launch.actions.DeclareLaunchArgument(
                name="record_on_startup",
                default_value="True",
                description="Enable/disable recording the simulation on startup. ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_sensor_recording",
                default_value="True",
                description="Enable/disable recording the sensor feed data (e.g. /carla/*/rgb_camera/*). ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_simulation_topic_recording",
                default_value="True",
                description="Enable/disable recording simulation topics (e.g. /carla/*). ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="enable_competition_topic_recording",
                default_value="True",
                description="Enable/disable recording competition topics (e.g. /competitor/*). ",
            ),
            launch.actions.DeclareLaunchArgument(
                name="recording_file_name",
                default_value=datetime.datetime.now().strftime("scenario_recording_%Y_%m_%d-%H_%M_%S.bag"),
                description="Path of the file generated by the recorder. ",
            ),
            dtcvc_scenario_node,
            dtcvc_timekeeper_node,
            dtcvc_recorder_node,
        ]
    )
    return ld


if __name__ == "__main__":
    generate_launch_description()
