class SensorLoadouts:
    sensor_configs = {
        "ouster_64" : {"sensor_type" : "sensor.lidar.ray_cast",
                       "attributes"  : {"range"                 : "50",
                                        "channels"              : "64",
                                        "points_per_second"     : "2621440",
                                        "upper_fov"             : "22.5",
                                        "lower_fov"             : "-22.5",
                                        "rotation_frequency"    : "60",
                                        "sensor_tick"           : "0.1",
                                        "noise_stddev"          : "0.01",
                                    },
                    },
        "generic_radar"     : {"sensor_type" : "sensor.other.radar",
                               "attributes"  : {"horizontal_fov"        : "30",
                                                "vertical_fov"          : "30",
                                                "range"                 : "50",
                                                "sensor_tick"           : "0.1",
                                            },
                    },
        "generic_rgb_camera"   : {"sensor_type" : "sensor.camera.rgb",
                                  "attributes"  : {"image_size_x"          : "1920",
                                                   "image_size_y"          : "1200",
                                                   "fov"                   : "90.0",
                                                   "sensor_tick"           : "0.05",
                                                },
                    },
        "generic_ir"        : {"sensor_type" : "sensor.camera.ir",
                                  "attributes"  : {"sensor_tick"           : "0.05",
                                                   "image_size_x"          : "640",
                                                   "image_size_y"          : "480",
                                                   "fov"                   : "90.0"
                                                },
                    },
        "generic_gps"      : {"sensor_type" : "sensor.other.gnss",
                              "attributes"  : {"sensor_tick"           : "0.01667",
                                               "noise_lat_stddev"      : "0.00000000000001",
                                               "noise_lon_stddev"      : "0.00000000000001",
                                               "noise_alt_stddev"      : "0.00000000000001",
                                        },
                    },
        "generic_imu"       : {"sensor_type" : "sensor.other.imu",
                               "attributes"  : {"sensor_tick"           : "0.01667",
                                                "noise_accel_stddev_x"  : "0.001",
                                                "noise_accel_stddev_y"  : "0.001",
                                                "noise_accel_stddev_z"  : "0.001",
                                                "noise_gyro_stddev_x"   : "0.001",
                                                "noise_gyro_stddev_y"   : "0.001",
                                                "noise_gyro_stddev_z"   : "0.001",
                                            },
                    },
        "generic_audio"     : {"sensor_type" : "sensor.other.audio",
                               "attributes"  : {"sensor_tick"           : "0.5",
                                            },
                    },
        "generic_template_sensor" : {"sensor_type" : "sensor.other.template",
                                     "attributes"  : {"sensor_tick"           : "0.05"
                                                      },
                    },
    }
