services:
  simulator:
    image: ${DTCVC_SIMULATOR_IMAGE:-dtcvc-simulator:latest}
    # Ensure GPU is available within the container
    # runtime: nvidia
    volumes:
      # Expose the host's X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DTCVC_PLATFORM=${DTCVC_PLATFORM:-linux}
      - DTCVC_NO_SIM_MODE=${DTCVC_NO_SIM_MODE:-false}
      - DTCVC_SIM_PORT=${DTCVC_SIM_PORT:-2000}
      - ROS_DISCOVERY_SERVER=${DTCVC_DISCOVERY_ADDRESS:-discovery}:${DTCVC_DISCOVERY_PORT:-11811}
    # The dtcvc-simulator entrypoint is a bash script which requires an interactive terminal
    # tty: true
    # Test to see if the CARLA API port is open
    healthcheck:
      test: netstat -ltn | grep -c ":2000"
      interval: 5s
      timeout: 3s
      retries: 30
