"""Defines the keys that will be present in a final report."""
SCORED_CASUALTIES: str = "scored_casualties"
INITIAL: str = "initial"
UPDATE: str = "update"
REPORT: str = "report"
CORRECT: str = "correct"
SCORE: str = "score"
GT_LOC: str = "gt_loc"
LOCATION: str = "location"
LATITUDE: str = "latitude"
LONGITUDE: str = "longitude"
ALTITUDE: str = "altitude"
ERROR: str = "error"
REPORTS: str = "reports"
RUNTIME: str = "runtime"
FINAL_SCORE: str = "runtime"
